config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :messages do
    resources :likes, only: [:create, :destroy]
    collection do
      get 'search'
    end
  end
  root to: "messages#index"
  resources :users, only: [:edit, :update]
  resources :likes, only: [:index]
  
  post '/messages/:message_id/likes' => "likes#create"
  delete '/messages/:message_id/likes' => "likes#destroy"
  
  devise_scope :user do
    get 'user_edit', to: 'users/registrations#user_edit', as: 'user_edit'
    patch 'user_update', to: 'users/registrations#user_update', as: 'user_update'
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :message, counter_cache: :likes_count
  belongs_to :user
end

app/models/message.rb
class Message < ApplicationRecord
  validates :text, presence: true
  validates :title, presence: true

  has_many :likes, dependent: :destroy
  belongs_to :user, optional: true
  # has_many :likes

  def likes_user(user_id)
    likes.find_by(user_id: user_id)
  end

  def self.search(search)
    return Message.all unless search
    Message.where('text LIKE(?)', "%#{search}%")
  end

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  validates :name, presence: true
  has_many :likes
  has_many :messages
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  protect_from_forgery with: :exception
  before_action :authenticate_user!
  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
    devise_parameter_sanitizer.permit(:sign_in, keys: [:name])
    devise_parameter_sanitizer.permit(:account_update, keys: [:name])
  end

end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
 
  before_action :set_like, except: :index


  def index
  end

  def create
    @like = Like.create(user_id: current_user.id, message_id: @message.id)
    # redirect_to messages_path
    respond_to do |format|
      format.html { redirect_to :root }
      format.json { render json: @like}
    end
  end

  def destroy
    @like = Like.find_by(user_id: current_user.id, message_id: @message.id)
    respond_to do |format|
      format.html { redirect_to :root }
      format.json { render json: @like}
    end
    @like.destroy
    # redirect_to messages_path
  end

  private
  def set_like
    @message = Message.find(params[:message_id])
  end

   # berfore_action :like_params

  # def create
  #   @like = Like.create(user_id: current_user.id, message_id: params[:message_id])
  #   @likes = Like.where(message_id: params[:message_id])
  #   # @messages = Message.all
  #   redirect_to messages_path
  # end

  # def destroy
  #   like = Like.find_by(user_id: current_user.id, message_id: params[:message_id])
  #   like.destroy
  #   @likes = Like.where(message_id: params[:message_id])
  #   # @messages = Message.all
  #   redirect_to messages_path
  # end
  # private

  # def like_params
  #   @messages = Message.find(params[:message_id])
  # end

end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  def index
    @messages = Message.all.order(created_at: :desc)
  end
  def new
    @message = Message.new
  end
  
  def create
    @message = Message.new(message_params)
    if @message.save
      redirect_to root_path, notice: 'メッセージを投稿しました'
    else
      redirect_to new_message_path, notice: '空欄を記入してください'
    end
  end

  def show
    @message = Message.find(params[:id])
  end

  def edit
    @message = Message.find(params[:id])
  end

  def update
    @message = Message.find(params[:id])
    @message.update(message_params)
    redirect_to root_path(@message), notice: 'メッセージを編集しました'
  end

  def destroy
    message = Message.find(params[:id])
    message.destroy
    redirect_to root_path(@messge), notice: 'メッセージを削除しました'
  end

  def search
    @messages = Message.search(params[:keyword])
  end

  private
  def message_params
    params.require(:message).permit(:title, :image, :text)
  end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  def edit
  end

  def user_update
    current_user.assign_attributes(account_update_params)
    if current_user.save
	  redirect_to root_path, notice: 'プロフィールを更新しました'
    else
      render "user_edit"
    end
  end
  
  private

  def user_params
    params.require(:user).permit(:name, :email)
  end
  
  protected
  
  def configure_account_update_params
   devise_parameter_sanitizer.permit(:account_update, keys: [:name])
  end

end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def edit
  end

  def update
    current_user.update(user_params)
    redirect_to root_path, notice: 'プロフィールを更新しました'
  end

  private

  def user_params
    params.require(:user).permit(:name, :email)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_notifications.html.haml
.notification
  - flash.each do |key, value|
    = content_tag :div, value, class: key

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title Study App
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
    %link{:crossorigin => "anonymous", :href => "https://use.fontawesome.com/releases/v5.8.2/css/all.css", :integrity => "sha384-oS3vJWv+0UjzBfQzYUhtDYW+Pj2yciDJxpsK1OYPAYjqT085Qq/1cq5FLXAZQ7Ay", :rel => "stylesheet"}/
  %header
    .header
      .header-top
        .header-left
          .foo
            - if user_signed_in?
              %span.letter{"data-letter" => "Study App"} Study App
              = link_to "/messages", class: "header-home" do
                = icon('fas', 'home')
              = link_to "/messages/new", class: "header-pen" do
                = icon('fas', 'pen')
            - else
              %span.letter{"data-letter" => "Study App"} Study App
              = link_to "/messages", class: "header-home" do
                = icon('fas', 'home')

      -# - if user_signed_in?
      -#   = current_user.name
      -# = link_to "ログアウト", destroy_user_session_path, method: :delete
      -#   = icon('fas', 'sign-out-alt')
      -# - else
      -# = link_to "ログイン", new_user_session_path, class: 'post'
      -#   = icon('fas', 'sign-in-alt')
      -# = link_to "新規登録", new_user_registration_path, class: 'post'
      -#   = icon('fas', 'file-alt')
      -# = link_to "マイページ", "/messages/#{current_user.id}"

      .header-top
        .header-right-user
          - if user_signed_in?
            = link_to "#{current_user.name}さん", edit_user_registration_path(current_user.id), class: 'post-name'
            = link_to  "/users/sign_out", method: :delete, class: 'post-logout' do
              = icon('fas', 'sign-out-alt', "ログアウト")
          - else
            = link_to "/users/sign_in", class: 'post-login' do
              = icon('fas', 'sign-in-alt', "ログイン")
            = link_to "/users/sign_up", class: 'post-new' do
              = icon('fas', 'file-alt', "新規登録")
          = link_to " https://twitter.com/", class: "header-twitter" do
            = icon('fab', 'twitter')
          = link_to " https://youtube.com/", class: "header-youtube" do
            = icon('fab', 'youtube')
          = link_to "likes", class: "header-game" do
            = icon('fas', 'gamepad')
          = link_to "#", class: "header-bars" do
            = icon('fas', 'bars')
  %body
    = render 'layouts/notifications', class: 'notifications'
    = yield

app/views/likes/_likes.html.haml
-# - if user_signed_in?
-#   - if message.like_user(current_user.id)
-#     = button_to message_like_path(message.likes_count, message_id: message.id), method: :delete, id: "like-button", remote: true do
-#       = icon('fas', 'check',)
-#       = "復習済"
-#       -# = message.likes_count
-#   - else
-#     = button_to message_likes_path(message), id: "like-button", remote: true do
-#       = icon('fas', 'exclamation-triangle')
-#       = "再復習"
-# - else
-#   = icon('fas', 'hand-peace')
  -# = message.likes_count

app/views/messages/_like.html.haml
- if user_signed_in?
  - if Like.find_by(user_id: current_user.id, message_id: message.id)
    = link_to "/messages/#{message.id}/likes", method: :delete, class: 'like-check', remote: true do
      = icon('fas', 'check')
      = "復習済"
  - else
    = link_to "/messages/#{message.id}/likes", method: :post, class: 'like-exclamation', remote: true do
      = icon('fas', 'exclamation-triangle')
      = "再復習"
- else
-# - if user_signed_in?
-#   - if message.likes_user(current_user.id)
-#     = button_to message_likes_path(message.likes_count, message_id: message.id), method: :delete, id: "like-button", remote: true do
-#       = icon('fas', 'check',)
-#       = "復習済"
-#       -# = message.likes_count
-#   - else
-#     = button_to message_likes_path(message), id: "like-button", remote: true do
-#       = icon('fas', 'exclamation-triangle')
-#       = "再復習"
-# - else
-#   = icon('fas', 'hand-peace')
  -# = message.likes_count
  -# = message.likes.length

app/views/messages/edit.html.haml
.contents.row
  .container
    = form_with(model: @message, local: true) do |form|
      %h3
        = "投稿"
        .container-form
          .container-form-title
            = form.text_field :title, placeholder: "title"
          .container-form-text
            = form.text_area :text, placeholder: "text" , rows: "10",'data-provider': :summernote
          .button
            %a.bnt-massage
              = form.submit "編集"
              %span 押してください.

app/views/messages/index.html.haml
- if user_signed_in?
  .message
    .message-main
      -# .message-form
      .message-side
        .side-search
          = form_with(url: search_messages_path, local: true, method: :get) do |form|
            = form.text_field :keyword, placeholder: "投稿を検索", class: 'search-field'
            = form.submit "検索"
        .side-weather
          = "今日の天気:"
          #weather.bold
          #weatherMark.bold
          #icon
          気温
          %span#temp.bold>
          ℃
          %br/
          降水確率
          %span#humidity.bold>
          ％
      .message-form
        - @messages.each do |message|
          .message-header
            .message-created
              = message.created_at.strftime("%m月%d")
            .message-title
              = message.title
          .message-header-left
            .message-like
              -# - if user_signed_in?
              = render partial: "like", locals: { message: message }
            .message-action
              .btn-open
                = link_to "編集", edit_message_path(message.id), class: 'message-edit'
              .btn-open
                = link_to '詳細', "/messages/#{message.id}", method: :get, class: 'message-show'
              .btn-open
                = link_to '削除', message_path(message.id), method: :delete, class: 'message-delete', data: { confirm: "削除しますか？"}
            .message-name
          .message-text
            = message.text.html_safe

            -# = current_user.name
            -#   - if message.like_user(current_user.id)
            -#     = button_to message_like_path(message.likes_count, message_id: message.id), method: :delete, id: "like-button", remote: true do
            -#       = icon('fas', 'check',)
            -#       = "復習済"
            -#       -# = message.likes_count
            -#   - else
            -#     = button_to message_likes_path(message), id: "like-button", remote: true do
            -#       = icon('fas', 'exclamation-triangle')
            -#       = "再復習"
            -# - else
            -#   = icon('fas', 'hand-peace')
            -#   = message.likes_count
-# - if user_signed_in?
-# - if messages.like_user(current_user.id)
-# = button_to messages_like_path(like, message_id: message.id), method: :delete, id: "like-button", remote: true do
-# = @likes
-# - if user_signed_in?
-# @likes_count          
-# .content_post{:style => "background-image: url(#{message.image});"}

app/views/messages/new.html.haml
.contents.row
  .container
    = form_with(model: @message, local: true) do |form|
      %h3
        = "投稿"
        .container-form
          .container-form-title
            = form.text_field :title, placeholder: "title"
          .container-form-text
            = form.text_area :text, placeholder: "text" , rows: "10",'data-provider': :summernote
            .button
              %a.bnt-massage
                = form.submit "送信"
                %span 押してください.

app/views/messages/search.html.haml
- @messages.each do |message|
  .show
    .show-header
      .show-created
        = message.created_at.strftime("%m月%d")
      .show-title
        = message.title
    .show-header-right
      .show-text
        = message.text.html_safe

app/views/messages/show.html.haml
.show
  .show-header
    .show-created
      = @message.created_at.strftime("%m月%d")
    .show-title
      = @message.title
  .show-header-right
    .show-text
      = @message.text.html_safe
-# = @show.text.html_safe